---
# Step 1. Install necesary dependencies
- name: Ensure all packages are up to date ... please wait!
  apt:
    update_cache: yes
    upgrade: dist
  become: true

- name: Install required dependencies
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg
    state: present
    update_cache: true
  become: true

# Step 2. Ensure the Kubernetes repository
- name: Add Kubernetes repository GPG key
  command: >
    curl -fsSL https://pkgs.k8s.io/core:/stable:/v1.34/deb/Release.key |
    gpg --dearmor -o /etc/apt/keyrings/kubernetes.gpg
  args:
    creates: /etc/apt/keyrings/kubernetes.gpg
  become: true

- name: Add Kubernetes repository
  copy:
    dest: /etc/apt/sources.list.d/kubernetes.list
    content: |
      deb [signed-by=/etc/apt/keyrings/kubernetes.gpg] https://pkgs.k8s.io/core:/stable:/v1.34/deb/ /
  become: true

# Step 3. Update and install kubernetes
- name: Update apt cache
  apt:
    update_cache: yes
  become: true

- name: Install Kubernetes components
  apt:
    name:
      - kubelet
      - kubeadm
      - kubectl
    state: present
  become: true

- name: Mark Kubernetes packages to hold
  apt:
    name:
      - kubelet
      - kubeadm
      - kubectl
    state: present
    force: yes
    mark_hold: true
  become: true

- name: Enable and restart kubelet
  systemd:
    name: kubelet
    enabled: true
    state: restarted
  become: true
