---
- name: Configuraci칩n b치sica de servidores Debian
  hosts: debian
  become: yes

  tasks:
    - name: Actualizar cache de paquetes (v치lido por 1 hora)
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Instalar paquetes b치sicos
      apt:
        name:
          - curl
          - wget
          - vim
        state: present
        update_cache: yes
